# Generated by Django 4.0.3 on 2022-05-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0002_student_age_student_date_of_birth_student_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=12),
        ),
    ]
