# Generated by Django 4.0.3 on 2022-05-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0004_student_date_of_birth_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
