# Generated by Django 4.0.3 on 2022-05-07 18:11

import basicform.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0005_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default=basicform.models.Student.pkgen, max_length=10, primary_key=True, serialize=False),
        ),
    ]
