# Generated by Django 4.0.4 on 2022-05-10 11:13

import basicform.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0007_finalstudent_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalstudent',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='telephone',
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='Blood_group',
            field=models.CharField(default='o', max_length=3),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='District',
            field=models.CharField(default='o', max_length=30),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='HSC_board_marks',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='Jee_percentile',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='MHTCET_percentile',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='Religion',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='SSC_board_marks',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='Student_mobile',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='Tele_phone',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='academic_year',
            field=models.CharField(default='2021-22', max_length=20),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='annual_income',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='area',
            field=models.CharField(choices=[('rural', 'rural'), ('urban', 'urban')], default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='board',
            field=models.CharField(choices=[('MH', 'maharashtra'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('Other', 'Other')], default='MH', max_length=10),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='cap_round',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='caste',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='category',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='college_address',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='college_name',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='country',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='domacile',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='father_email',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='father_name',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='father_occupation',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='local_address',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='mobile_number',
            field=models.CharField(default='o', max_length=10),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='mother_email',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='mother_name',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='nationality',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='passing_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='permanent_address',
            field=models.CharField(default='urban', max_length=200),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='pin_code',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='place_of_birth',
            field=models.CharField(default='o', max_length=30),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='quota',
            field=models.CharField(choices=[('institute', 'insti. lvl'), ('pio', 'pio,J&K,J&kSSS'), ('NEUT', 'NEUT'), ('OCI', 'OCI'), ('FN', 'FN'), ('CIWC', 'CIWC')], default='institute', max_length=20),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='state',
            field=models.CharField(choices=[('MS', 'MS'), ('OMS', 'OMS')], default='MS', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='Blood_group',
            field=models.CharField(default='o', max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='District',
            field=models.CharField(default='o', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='HSC_board_marks',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='Jee_percentile',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='MHTCET_percentile',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='Religion',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='SSC_board_marks',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='Student_mobile',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='Tele_phone',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(default='2021-22', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='annual_income',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='area',
            field=models.CharField(choices=[('rural', 'rural'), ('urban', 'urban')], default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='board',
            field=models.CharField(choices=[('MH', 'maharashtra'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('Other', 'Other')], default='MH', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='cap_round',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='caste',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='college_address',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='college_name',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='domacile',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='father_email',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='local_address',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(default='o', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_email',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='passing_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.CharField(default='urban', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='pin_code',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(default='o', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='quota',
            field=models.CharField(choices=[('institute', 'insti. lvl'), ('pio', 'pio,J&K,J&kSSS'), ('NEUT', 'NEUT'), ('OCI', 'OCI'), ('FN', 'FN'), ('CIWC', 'CIWC')], default='institute', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('MS', 'MS'), ('OMS', 'OMS')], default='MS', max_length=30),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='date_of_birth',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='first_name',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='last_name',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default=basicform.models.Student.pkgen, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='o', max_length=200),
        ),
    ]
