# Generated by Django 4.0.3 on 2022-05-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0008_remove_finalstudent_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalstudent',
            name='branch',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Data Science', 'Data Science'), ('IT', 'IT'), ('ENTC', 'ENTC')], default='Computer', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Data Science', 'Data Science'), ('IT', 'IT'), ('ENTC', 'ENTC')], default='Computer', max_length=20),
        ),
    ]
