# Generated by Django 4.0.3 on 2022-05-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0009_finalstudent_branch_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalstudent',
            name='reg_no',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
