# Generated by Django 4.0.3 on 2022-05-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0010_finalstudent_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalstudent',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
