# Generated by Django 4.0.3 on 2022-05-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0011_alter_finalstudent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalstudent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
