# Generated by Django 4.0.3 on 2022-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0013_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempStudents',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default='o', max_length=200)),
                ('last_name', models.CharField(default='o', max_length=200)),
            ],
        ),
    ]
