# Generated by Django 4.0.3 on 2022-06-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0014_tempstudents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempStudents',
        ),
    ]
