# Generated by Django 4.0.3 on 2022-06-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0015_delete_tempstudents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalstudent',
            old_name='board',
            new_name='HSC_board',
        ),
        migrations.RenameField(
            model_name='finalstudent',
            old_name='father_name',
            new_name='father_first_name',
        ),
        migrations.RenameField(
            model_name='finalstudent',
            old_name='mother_name',
            new_name='mother_first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='board',
            new_name='HSC_board',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='father_name',
            new_name='father_first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mother_name',
            new_name='mother_first_name',
        ),
        migrations.RemoveField(
            model_name='finalstudent',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='HSC_pcm',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='SSC_board',
            field=models.CharField(choices=[('MH', 'maharashtra'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('Other', 'Other')], default='MH', max_length=10),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='aadhar_no',
            field=models.IntegerField(default=55555),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='email',
            field=models.EmailField(default='xyz@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='father_last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='father_middle_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='father_mobile',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='first_attempt',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='marksheet_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='mother_middle_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='mother_mobile',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='other_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='seat_type',
            field=models.CharField(default='o', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='HSC_pcm',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='SSC_board',
            field=models.CharField(choices=[('MH', 'maharashtra'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('Other', 'Other')], default='MH', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='aadhar_no',
            field=models.IntegerField(default=55555),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='xyz@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='father_last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='father_middle_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='father_mobile',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='first_attempt',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='marksheet_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_middle_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_mobile',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='other_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='seat_type',
            field=models.CharField(default='o', max_length=100),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='Student_mobile',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='Tele_phone',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='category',
            field=models.CharField(choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('general', 'general'), ('VJNT', 'VJNT')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='father_email',
            field=models.EmailField(default='xyz@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='mobile_number',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='mother_email',
            field=models.EmailField(default='xyz@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='passing_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_mobile',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='Tele_phone',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('general', 'general'), ('VJNT', 'VJNT')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_email',
            field=models.EmailField(default='xyz@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_email',
            field=models.EmailField(default='xyz@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='passing_year',
            field=models.DateField(),
        ),
    ]
