# Generated by Django 4.0.3 on 2022-06-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0016_rename_board_finalstudent_hsc_board_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalstudent',
            old_name='Jee_percentile',
            new_name='Jee_main_percentile',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Jee_percentile',
            new_name='Jee_main_percentile',
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='Jee_adv_percentile',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='Jee_adv_percentile',
            field=models.FloatField(default=1),
        ),
    ]
