# Generated by Django 4.0.3 on 2022-06-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0018_remove_finalstudent_ssc_board_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalstudent',
            name='subcaste',
            field=models.CharField(default='o', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='subcaste',
            field=models.CharField(default='o', max_length=20),
        ),
    ]
