# Generated by Django 4.0.3 on 2022-06-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0021_rename_domacile_finalstudent_domicile'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalstudent',
            name='middle_name',
            field=models.CharField(default='o', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(default='o', max_length=200),
        ),
    ]
