# Generated by Django 4.0.3 on 2022-06-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0022_finalstudent_middle_name_student_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalstudent',
            name='reg_no',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='cap_round',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='quota',
            field=models.CharField(choices=[('institute', 'insti. lvl'), ('pio', 'pio,J&K,J&kSSS'), ('NEUT', 'NEUT'), ('OCI', 'OCI'), ('FN', 'FN'), ('CIWC', 'CIWC'), ('TFWS', 'TFWS'), ('EWS', 'EWS'), ('DEF', 'DEF')], default='institute', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='cap_round',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='quota',
            field=models.CharField(choices=[('institute', 'insti. lvl'), ('pio', 'pio,J&K,J&kSSS'), ('NEUT', 'NEUT'), ('OCI', 'OCI'), ('FN', 'FN'), ('CIWC', 'CIWC'), ('TFWS', 'TFWS'), ('EWS', 'EWS'), ('DEF', 'DEF')], default='institute', max_length=20),
        ),
    ]
