# Generated by Django 4.0.3 on 2022-06-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0024_alter_finalstudent_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='passing_year',
            field=models.CharField(max_length=100),
        ),
    ]
