# Generated by Django 4.0.6 on 2022-08-21 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0031_branch_clss_subject_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='basicform.clss'),
            preserve_default=False,
        ),
    ]
