# Generated by Django 4.0.6 on 2022-08-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0032_subject_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPost',
            fields=[
                ('post_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('Teaching', 'Teaching'), ('Non Teaching', 'Non Teaching')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('emp_code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('post_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicform.fpost')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicform.subject')),
            ],
        ),
    ]
