# Generated by Django 4.0.6 on 2022-08-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0033_fpost_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpost',
            name='post_type',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
