# Generated by Django 4.0.6 on 2022-08-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0034_remove_fpost_post_type_delete_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpost',
            name='post_type',
            field=models.CharField(choices=[('Teaching', 'Teaching'), ('Non Teaching', 'Non Teaching')], default='Teaching', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('emp_code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('post_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicform.fpost')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicform.subject')),
            ],
        ),
    ]
