# Generated by Django 4.0.6 on 2022-08-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0035_fpost_post_type_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicform.faculty'),
        ),
    ]
