# Generated by Django 4.0.6 on 2022-08-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0036_remove_faculty_subject_subject_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='branch',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
