# Generated by Django 4.0.6 on 2022-08-22 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0037_faculty_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='branch',
        ),
        migrations.AddField(
            model_name='faculty',
            name='branch_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicform.branch'),
        ),
    ]
