# Generated by Django 4.0.6 on 2022-09-02 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0039_subject_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalstudent',
            name='class_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicform.clss'),
        ),
        migrations.AddField(
            model_name='finalstudent',
            name='division',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicform.division'),
        ),
        migrations.AlterField(
            model_name='deletedstudent',
            name='branch',
            field=models.CharField(default='Computer', max_length=20),
        ),
        migrations.AlterField(
            model_name='finalstudent',
            name='branch',
            field=models.CharField(default='Computer', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(default='Computer', max_length=20),
        ),
    ]
