# Generated by Django 4.0.6 on 2022-09-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0040_finalstudent_class_name_finalstudent_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedstudent',
            name='class_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicform.clss'),
        ),
        migrations.AddField(
            model_name='deletedstudent',
            name='division',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicform.division'),
        ),
    ]
