# Generated by Django 4.0.6 on 2022-10-19 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0041_deletedstudent_class_name_deletedstudent_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('time_slot', models.CharField(max_length=10)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicform.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('date', models.CharField(max_length=10)),
                ('timeobj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basicform.timetable')),
            ],
        ),
    ]
