# Generated by Django 4.0.6 on 2022-10-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0043_remove_timetable_subject_delete_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reg_no', models.CharField(max_length=11)),
                ('duration', models.IntegerField()),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
    ]
