# Generated by Django 4.0.6 on 2022-10-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0044_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicform.finalstudent'),
        ),
    ]
