# Generated by Django 4.0.6 on 2022-10-25 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0051_alter_attendance_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='reg_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicform.finalstudent'),
        ),
    ]
